# Generated by Django 4.1.3 on 2022-11-21 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=255, verbose_name='Doctor Name')),
                ('dmobile', models.CharField(max_length=15, verbose_name='Doctor Contact Number')),
                ('qualification', models.CharField(max_length=255)),
                ('specialist', models.CharField(max_length=255)),
                ('yoe', models.CharField(max_length=2, verbose_name='Year of Experience')),
            ],
        ),
        migrations.AlterField(
            model_name='mobile',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
    ]
